-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS myscheme.films
(
    film_id serial NOT NULL,
    title character varying(100) NOT NULL,
    release_year smallint NOT NULL,
    genre_id integer NOT NULL,
    rating numeric(3) NOT NULL,
    duration smallint NOT NULL,
    description character varying(300) NOT NULL,
    PRIMARY KEY (film_id)
);

CREATE TABLE IF NOT EXISTS myscheme.directors
(
    director_id serial NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(30) NOT NULL,
    birth_date date NOT NULL,
    nationality character varying(20) NOT NULL,
    PRIMARY KEY (director_id)
);

CREATE TABLE IF NOT EXISTS myscheme.actors
(
    actor_id serial NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(30) NOT NULL,
    birth_date date NOT NULL,
    nationality character varying(30) NOT NULL,
    PRIMARY KEY (actor_id)
);

CREATE TABLE IF NOT EXISTS myscheme.film_directors
(
    id serial NOT NULL,
    film_id integer NOT NULL,
    director_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS myscheme.film_actors
(
    id serial NOT NULL,
    film_id integer NOT NULL,
    actor_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS myscheme.customers
(
    customer_id serial NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(30) NOT NULL,
    email character varying(30) NOT NULL,
    phone character varying(20) NOT NULL,
    address character varying(100) NOT NULL,
    PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS myscheme.rentals
(
    rental_id serial NOT NULL,
    customer_id integer NOT NULL,
    film_id integer NOT NULL,
    rental_date date NOT NULL,
    return_date date NOT NULL,
    PRIMARY KEY (rental_id)
);

CREATE TABLE IF NOT EXISTS myscheme.genres
(
    genre_id serial NOT NULL,
    genre_name character varying(30) NOT NULL,
    PRIMARY KEY (genre_id)
);

ALTER TABLE IF EXISTS myscheme.films
    ADD FOREIGN KEY (genre_id)
    REFERENCES myscheme.genres (genre_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS myscheme.film_directors
    ADD FOREIGN KEY (film_id)
    REFERENCES myscheme.films (film_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS myscheme.film_directors
    ADD FOREIGN KEY (director_id)
    REFERENCES myscheme.directors (director_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS myscheme.film_actors
    ADD FOREIGN KEY (film_id)
    REFERENCES myscheme.films (film_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS myscheme.film_actors
    ADD FOREIGN KEY (actor_id)
    REFERENCES myscheme.actors (actor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS myscheme.rentals
    ADD FOREIGN KEY (customer_id)
    REFERENCES myscheme.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS myscheme.rentals
    ADD FOREIGN KEY (film_id)
    REFERENCES myscheme.films (film_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;